import Button from "@/components/button.component";
import Head from "next/head";

export default function Home() {
  const handleSubmit = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
    e.preventDefault();

    const quantity = document.getElementById("quantity") as HTMLInputElement;
    quantity.value &&
    Number(quantity.value) > 0 &&
    Number(quantity.value) < 1000
      ? (alert("Vagas cadastradas com sucesso!"),
        localStorage.setItem("vagas", quantity.value))
      : alert("O número de vagas deve ser maior que 0 e menor que 1000.");
  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container ">
        <div>
          <div className="page-title">
            <h1>Página Principal</h1>
          </div>
          <form className="form-flex">
            <label htmlFor="quantity">
              Digite quantas vagas o estacionamento tem:
            </label>
            <p>
              <strong>Obs:</strong> O número de vagas deve ser maior que 0 e
              menor que 1000.
            </p>
            <div>
              <input type="number" id="quantity" />
              <Button onClick={(e) => handleSubmit(e)} type="submit">
                Enviar
              </Button>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}
